[project]
name = "medical-symptoms-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=1.2.6",
    "langchain-elasticsearch>=1.0.0",
    "langchain-openai>=1.1.6",
]
